name: data-view

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12,3.13]
    services:
      db:
        image: postgres:17.2
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./data-view/requirements.txt
    - name: Run Tests
      env:
        DEBUG: "1"
        SECRET_KEY: "DjangoSecretKey"
        DJANGO_ALLOWED_HOSTS: "*"
        DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost"
        SQL_ENGINE: "django.db.backends.postgresql"
        SQL_DATABASE: "db"
        SQL_USER: "user"
        SQL_PASSWORD: "password"
        SQL_HOST: "127.0.0.1"
        SQL_PORT: "5432"
        HOME_DIR: "/code"
        SESSION_SECRET: "SessionSecret"
        TIMEZONE: "Europe/Warsaw"

      working-directory: ./data-view
      run: |
        python manage.py test
