name: DataView CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Start services
        run: |
          docker compose -f github-ci-docker-compose.yml up -d --build # Uruchamia wszystkie kontenery, w tym libreoffice

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be ready..."
          sleep 15  # Opcjonalny delay, można zastąpić healthcheckiem

      - name: Run migrations
        run: |
          docker compose exec -T core python manage.py migrate

      - name: Run tests
        run: |
          docker compose exec -T core python manage.py test

      - name: Tear down
        if: always()
        run: docker compose down -v
