name: DataView CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: github-ci-docker-compose.yml  # Ustawienie domyślnego pliku Compose

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Start services
        run: |
          docker compose up -d --build  # Uruchamia wszystkie kontenery

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be ready..."
          sleep 15  # Opcjonalne oczekiwanie

      - name: Run migrations
        run: |
          docker compose exec -T core python data-view/manage.py migrate
      - name: Check media, static files and shared folder
        run: |
          docker compose exec -T core ls -la /shared/
          docker compose exec -T core ls -la /code/static
          docker compose exec -T core ls -la /code/media
      - name: Check LibreOffice
        run: |
          docker compose exec -T libreoffice soffice --version
      - name: Run tests
        run: |
          docker compose exec -T core python data-view/manage.py test ConversionAPI

      - name: Tear down
        if: always()
        run: docker compose down -v
